#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        systemctl stop sdr_scanner 2>/dev/null || true
        systemctl disable sdr_scanner 2>/dev/null || true
        systemctl stop sdr_hotspot 2>/dev/null || true
        systemctl disable sdr_hotspot 2>/dev/null || true
        rm -f /etc/sudoers.d/sdr-hotspot
    ;;
esac
